### ISSUE TITLE
Stack Trace is Very Noisy

### ISSUE THREAD

**Issue by Akamaozu** [groundwater/node-stackup#10]
Async listener dominates the stack trace now.

![image](https://cloud.githubusercontent.com/assets/1587024/21078877/9b58ebbc-bf4d-11e6-9844-4a4ac09c22a2.png)

**Comment by 0xcaff** [comment]
What is `demo.js`?

**Comment by Akamaozu** [comment]
https://github.com/groundwater/node-stackup/blob/master/demo.js
